### ISSUE TITLE
Incomplete Cache Files

### ISSUE THREAD

**Issue by marcusjb** [daneren2005/Subsonic#606] opened 2015-12-23 21:56 UTC
I have DSub set to wifi streaming only.  If leave a wifi network while a song is downloading Dsub leaves it as if it's complete and will even play half a song next time it comes around.  

Maybe if Dsub could compare the downloaded song to the server and toss it if they don't match.

**Comment by daneren2005** [comment] 2015-12-26 23:40
I can reproduce that it tries to play the song and fails halfway through because it isn't actually fully downloaded it, but I can't reproduce that it marks it as complete.  In my testing it leaves the percentage showing and when I try to restart DSub or switch which song I am playing it never gets marked as complete (ie: the three dots never change to a blue pin icon).  Am I missing a step to reproduce?

**Closed** 2015-12-31 18:23 UTC
