### ISSUE TITLE
Playback and caching (permanent and non-permanent) of files containing one or more slashes in artist tag

### ISSUE THREAD

**Issue by arno1979** [daneren2005/Subsonic#681] opened 2016-04-25 17:38 UTC
I just noticed a problem when trying to play a file from my ampache server.
This file is part of the Treme Season 2 Soundtrack. It's actually the second track. The first one played fine, on the second one the playback fails and it skips to the third track.
The same phanomenon occured on some of the other tracks of this album.
I then tried to manually cache the files - that didn't work either.
Then I noticed that the artists name of the problematic tracks all contained slahes. They are used to separate multiple artists for one track. When I manually replaced the slashes with dots on one track and tried again playback was successful.
As this album was tagged using the MusicBrainz database I would guess that it should be ok to use slashes (I know they can be problematic when not correctly escaped) for any tag field.
I haven't tested if the problem also occurs when a slash is used in another tag field.
Is there some thing that can be done about this problem?

Thanks
Arno

EDIT:
I just verified that a slash in a track name tag is NOT a problem. When I view the file system I can see that the slash is replaced by a dash in the file name. Maybe a similar mechanism could be used for folder names as well.

**Comment by daneren2005** [comment] 2016-04-27 03:43
I am honestly having trouble reproducing this.  As you mention in your edit the slash is replaced in the filename, but it should also be replaced in the artist.  It is using the same function to sanitize the title, artist, and album before saving to the filesystem.

**Comment by daneren2005** [comment] 2016-04-27 04:01
Nevermind, I figured it out.  I don't replace slashes when I am using the path given as part of the metadata.  The reason for this is because the path is often a full path (ie: path="artist/album/song.mp3").  Does Ampache put the tags in that field instead of putting in the actual file path?

**Comment by daneren2005** [comment] 2016-04-27 04:32
On my Ampache server I was able to verify that it was just throwing the artist/album tag into the path field which is not what it is supposed to be used for (specifically because you end up with crap like that).  I will play more with whether I want to try to add a work around to this or just pass it back to Ampache tomorrow.

**Comment by arno1979** [comment] 2016-04-27 12:12
Ok, great! Thanks for looking into it.

**Comment by daneren2005** [comment] 2016-04-27 20:11
While the path field does appear to be oddly specified, I don't think this is your problem.  For example if it is in the path as `This is/ my art/ist/album/song.mp3`, that will work just fine.  It won't be standard since it will be like 4 folders down instead of 2, but it should still work just fine since that is a perfectly valid path.  Have you tried checking your Ampache/nginx logs and making sure that it's actually returning a valid stream and not throwing an error on those files?

**Comment by arno1979** [comment] 2016-04-28 10:40
Maybe this will help: For testing and logging purposes I retagged one of the files that caused problems to include slashes in the artist tag again.
Following is all the information I could gather:

Original filename on server: 01-02 From the Corner to the Block.mp3
Tag information:
Song name: From the Corner to the Block
Artist: Galactic / Juvenile / The Dirty Dozen Brass Band
Album: Treme: Season 2
Album Artist: Various Artists

Apache log when trying to **playback** the file:
> [28/Apr/2016:11:49:57 +0200] "GET /play/index.php?ssid=c5d6f8c81c5f8ca36d36eff32a8538f9&type=song&oid=93171&uid=2&client=DSub&noscrobble=1&bitrate=259&player=api&name=Galactic%20-%20Juvenile%20-%20The%20Dirty%20Dozen%20Brass%20Band%20-%20From%20the%20Corner%20to%20the%20Block.mp3 HTTP/1.1" 200 7580284 "-" "DSub"
[28/Apr/2016:11:49:56 +0200] "POST /rest/stream.view?u=arno&p=enc:736537656e37&v=1.2.0&c=DSub&id=300093171&maxBitRate=259 HTTP/1.1" 200 7580284 "-" "DSub"
[28/Apr/2016:11:50:03 +0200] "GET /play/index.php?ssid=a4897cb41c01e10d8ad341b9b1225fc2&type=song&oid=93171&uid=2&client=DSub&noscrobble=1&bitrate=259&player=api&name=Galactic%20-%20Juvenile%20-%20The%20Dirty%20Dozen%20Brass%20Band%20-%20From%20the%20Corner%20to%20the%20Block.mp3 HTTP/1.1" 200 7580284 "-" "DSub"
[28/Apr/2016:11:50:02 +0200] "POST /rest/stream.view?u=arno&p=enc:736537656e37&v=1.2.0&c=DSub&id=300093171&maxBitRate=259 HTTP/1.1" 200 7580284 "-" "DSub"
[28/Apr/2016:11:50:10 +0200] "GET /play/index.php?ssid=df04cfa9dcde8ab3feaacde8ddf1c154&type=song&oid=93171&uid=2&client=DSub&noscrobble=1&bitrate=259&player=api&name=Galactic%20-%20Juvenile%20-%20The%20Dirty%20Dozen%20Brass%20Band%20-%20From%20the%20Corner%20to%20the%20Block.mp3 HTTP/1.1" 200 7580284 "-" "DSub"
[28/Apr/2016:11:50:10 +0200] "POST /rest/stream.view?u=arno&p=enc:736537656e37&v=1.2.0&c=DSub&id=300093171&maxBitRate=259 HTTP/1.1" 200 7580284 "-" "DSub"

Ampache log when trying to **playback** the file:
> 2016-04-28 11:54:14 [arno] (session) -> Session created: 751935e4efbbea2e712a8af7b9f123e6 
2016-04-28 11:54:14 [arno] (subsonic) -> Stream proxy: https://xxx.com:443/play/index.php?ssid=751935e4efbbea2e712a8af7b9f123e6&type=song&oid=93171&uid=2&client=DSub&noscrobble=1&bitrate=259&player=api&name=Galactic%20-%20Juvenile%20-%20The%20Dirty%20Dozen%20Brass%20Band%20-%20From%20the%20Corner%20to%20the%20Block.mp3 
2016-04-28 11:54:14 [ampache] (play) -> Asked for type {song} 
2016-04-28 11:54:14 [arno] (session) -> 751935e4efbbea2e712a8af7b9f123e6 has been extended to Thu, 28 Apr 2016 13:54:14 +0200 extension length 7200 
2016-04-28 11:54:14 [arno] (play) -> Playing file (/mnt/music/OST/Treme Season 2 OST - [2012]/01-02 From the Corner to the Block.mp3}... 
2016-04-28 11:54:14 [arno] (play) -> Media type {mp3} 
2016-04-28 11:54:14 [arno] (play) -> Custom play action {} 
2016-04-28 11:54:14 [arno] (play) -> Transcode to {} 
2016-04-28 11:54:14 [arno] (play) -> Transcoding is not enabled for this media type. Valid types: {["native"]} 
2016-04-28 11:54:14 [arno] (play) -> Starting stream of /mnt/music/OST/Treme Season 2 OST - [2012]/01-02 From the Corner to the Block.mp3 with size 7580284 
2016-04-28 11:54:14 [arno] (play) -> Registering stream stats for {Galactic / Juvenile / The Dirty Dozen Brass Band - From the Corner to the Block}... 
2016-04-28 11:54:14 [arno] (user.class.php) -> Updating stats for {song/93171} {DSub}... 
2016-04-28 11:54:14 [arno] (user.class.php) -> Scrobbling explicitly skipped 
2016-04-28 11:54:19 [arno] (play) -> Stream ended at 7580284 (7580284) bytes out of 7580284 

Apache log when trying to **permanently cache** the file:
> [28/Apr/2016:12:12:10 +0200] "GET /play/index.php?ssid=c88fadcd1468127e96d32f9f5866b4f8&type=song&oid=93171&uid=2&client=DSub&noscrobble=1&bitrate=259&player=api&name=Galactic%20-%20Juvenile%20-%20The%20Dirty%20Dozen%20Brass%20Band%20-%20From%20the%20Corner%20to%20the%20Block.mp3 HTTP/1.1" 200 7580284 "-" "DSub"
46.59.215.82 - - [28/Apr/2016:12:12:10 +0200] "POST /rest/stream.view?u=arno&p=enc:736537656e37&v=1.2.0&c=DSub&id=300093171&maxBitRate=259 HTTP/1.1" 200 7580284 "-" "DSub"

Ampache log when trying to **permanently cache** the file:
> 2016-04-28 11:56:26 [arno] (session) -> Session created: 247c0d65497a06dacb2f8042c64feb76 
2016-04-28 11:56:26 [arno] (subsonic) -> Stream proxy: https://xxx.com:443/play/index.php?ssid=247c0d65497a06dacb2f8042c64feb76&type=song&oid=93171&uid=2&client=DSub&noscrobble=1&bitrate=259&player=api&name=Galactic%20-%20Juvenile%20-%20The%20Dirty%20Dozen%20Brass%20Band%20-%20From%20the%20Corner%20to%20the%20Block.mp3 
2016-04-28 11:56:26 [ampache] (play) -> Asked for type {song} 
2016-04-28 11:56:26 [arno] (session) -> 247c0d65497a06dacb2f8042c64feb76 has been extended to Thu, 28 Apr 2016 13:56:26 +0200 extension length 7200 
2016-04-28 11:56:26 [arno] (play) -> Playing file (/mnt/music/OST/Treme Season 2 OST - [2012]/01-02 From the Corner to the Block.mp3}... 
2016-04-28 11:56:26 [arno] (play) -> Media type {mp3} 
2016-04-28 11:56:26 [arno] (play) -> Custom play action {} 
2016-04-28 11:56:26 [arno] (play) -> Transcode to {} 
2016-04-28 11:56:26 [arno] (play) -> Transcoding is not enabled for this media type. Valid types: {["native"]} 
2016-04-28 11:56:26 [arno] (play) -> Starting stream of /mnt/music/OST/Treme Season 2 OST - [2012]/01-02 From the Corner to the Block.mp3 with size 7580284 
2016-04-28 11:56:26 [arno] (play) -> Registering stream stats for {Galactic / Juvenile / The Dirty Dozen Brass Band - From the Corner to the Block}... 
2016-04-28 11:56:26 [arno] (user.class.php) -> Updating stats for {song/93171} {DSub}... 
2016-04-28 11:56:26 [arno] (user.class.php) -> Scrobbling explicitly skipped 
2016-04-28 11:56:31 [arno] (play) -> Stream ended at 7580284 (7580284) bytes out of 7580284 
2016-04-28 11:56:32 [arno] (session) -> Session created: e2708cc06aff928db07e4639eb4ee1cd 
2016-04-28 11:56:32 [arno] (subsonic) -> Stream proxy: https://xxx.com:443/play/index.php?ssid=e2708cc06aff928db07e4639eb4ee1cd&type=song&oid=93171&uid=2&client=DSub&noscrobble=1&bitrate=259&player=api&name=Galactic%20-%20Juvenile%20-%20The%20Dirty%20Dozen%20Brass%20Band%20-%20From%20the%20Corner%20to%20the%20Block.mp3 
2016-04-28 11:56:32 [ampache] (play) -> Asked for type {song} 
2016-04-28 11:56:32 [arno] (session) -> e2708cc06aff928db07e4639eb4ee1cd has been extended to Thu, 28 Apr 2016 13:56:32 +0200 extension length 7200 
2016-04-28 11:56:32 [arno] (play) -> Playing file (/mnt/music/OST/Treme Season 2 OST - [2012]/01-02 From the Corner to the Block.mp3}... 
2016-04-28 11:56:32 [arno] (play) -> Media type {mp3} 
2016-04-28 11:56:32 [arno] (play) -> Custom play action {} 
2016-04-28 11:56:32 [arno] (play) -> Transcode to {} 
2016-04-28 11:56:32 [arno] (play) -> Transcoding is not enabled for this media type. Valid types: {["native"]} 
2016-04-28 11:56:32 [arno] (play) -> Starting stream of /mnt/music/OST/Treme Season 2 OST - [2012]/01-02 From the Corner to the Block.mp3 with size 7580284 
2016-04-28 11:56:32 [arno] (play) -> Registering stream stats for {Galactic / Juvenile / The Dirty Dozen Brass Band - From the Corner to the Block}... 
2016-04-28 11:56:32 [arno] (user.class.php) -> Updating stats for {song/93171} {DSub}... 
2016-04-28 11:56:32 [arno] (user.class.php) -> Scrobbling explicitly skipped 
2016-04-28 11:56:32 [arno] (statistics) -> Statistics insertion ignored due to graceful delay. 
2016-04-28 11:56:32 [arno] (statistics) -> Statistics insertion ignored due to graceful delay. 
2016-04-28 11:56:32 [arno] (statistics) -> Statistics insertion ignored due to graceful delay. 
2016-04-28 11:56:41 [arno] (play) -> Stream ended at 7580284 (7580284) bytes out of 7580284 
2016-04-28 11:56:41 [arno] (session) -> Session created: 097329b140c58eec3081e84fd68e2924 
2016-04-28 11:56:41 [arno] (subsonic) -> Stream proxy: https://xxx.com:443/play/index.php?ssid=097329b140c58eec3081e84fd68e2924&type=song&oid=93171&uid=2&client=DSub&noscrobble=1&bitrate=259&player=api&name=Galactic%20-%20Juvenile%20-%20The%20Dirty%20Dozen%20Brass%20Band%20-%20From%20the%20Corner%20to%20the%20Block.mp3 
2016-04-28 11:56:42 [ampache] (play) -> Asked for type {song} 
2016-04-28 11:56:42 [arno] (session) -> 097329b140c58eec3081e84fd68e2924 has been extended to Thu, 28 Apr 2016 13:56:42 +0200 extension length 7200 
2016-04-28 11:56:42 [arno] (play) -> Playing file (/mnt/music/OST/Treme Season 2 OST - [2012]/01-02 From the Corner to the Block.mp3}... 
2016-04-28 11:56:42 [arno] (play) -> Media type {mp3} 
2016-04-28 11:56:42 [arno] (play) -> Custom play action {} 
2016-04-28 11:56:42 [arno] (play) -> Transcode to {} 
2016-04-28 11:56:42 [arno] (play) -> Transcoding is not enabled for this media type. Valid types: {["native"]} 
2016-04-28 11:56:42 [arno] (play) -> Starting stream of /mnt/music/OST/Treme Season 2 OST - [2012]/01-02 From the Corner to the Block.mp3 with size 7580284 
2016-04-28 11:56:42 [arno] (play) -> Registering stream stats for {Galactic / Juvenile / The Dirty Dozen Brass Band - From the Corner to the Block}... 
2016-04-28 11:56:42 [arno] (user.class.php) -> Updating stats for {song/93171} {DSub}... 
2016-04-28 11:56:42 [arno] (user.class.php) -> Scrobbling explicitly skipped 
2016-04-28 11:56:47 [arno] (play) -> Stream ended at 7580284 (7580284) bytes out of 7580284 

When I look into the android filesystem after trying to permanently cache the file I would expect a directory starting with "Galactic..." to have been created. This is not the case. Nothing happened there.
When I retag the file and change the slashes to "&" again a directory named "Galactic & Juvenile..." is instantly created.

So the problem - as far as I can tell - lies not within the path names but in the fact that the path is not created if the artists name contains slashes.

**Comment by daneren2005** [comment] 2016-04-28 23:40
Alright can you try download one of those failed songs, then send me a log via the Home tab -> three dot menu -> Send Logs?  There should be some relevant information on why it is failing in there.

**Comment by arno1979** [comment] 2016-04-29 08:27
I tried to do that but when pressing the "Send Logs" link I get a message "Failed to gather logs".

**Comment by daneren2005** [comment] 2016-04-29 19:24
I goofed and didn't include the Pastebin token in the last release.  I have updated the download link here on Github as well as the Play Store should be sending out an update soon.  After you get that try again.

**Comment by arno1979** [comment] 2016-04-30 08:37
I updated DSub and sent the logs. You should have received them now.

**Comment by daneren2005** [comment] 2016-04-30 16:56
Ok so it is failing to create the directory.  I don't understand why since it is visually valid, but oh well.  I am waiting for a response from https://github.com/ampache/ampache/issues/1213 before I decide whether to put a work around or wait for them to make the change.

**Comment by arno1979** [comment] 2016-04-30 17:23
My guess would be the blank spaces before and after the slashes. I haven't tested it though.

**Comment by daneren2005** [comment] 2016-04-30 17:35
I did with spaces before and after in my test too

**Comment by daneren2005** [comment] 2016-05-02 16:53
Alright Ampache is going to fix the path on their end so I am closing this.

**Closed by daneren2005** 2016-05-02 16:53 UTC
